# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  print_working_directory:
    runs-on: ubuntu-latest
    steps:
      - name: Printing the Working Directory Path
        run: |
          echo "I'm about to print da working directory..."
          pwd
          echo "I just printed the working directory path to the console"

  print_context:
    runs-on: ubuntu-latest
    needs: print_working_directory
    steps:
      - name: Printing the Context of this GitHub Workflow
        run: echo "${{ toJSON(github) }}" # prints the github context, which is provided automatically, and formats the JSON